### ISSUE TITLE
keywordize behaviour not consistent

### ISSUE THREAD

**Issue by jeroenvandijk** [owainlewis/yaml#11]
Thank you for this library. I'm playing a bit with it and notice that the `yaml/from-file` does not keywordize string by default where as `yaml/parse-string` does.

Here it's `false` https://github.com/owainlewis/yaml/blob/master/src/yaml/core.clj#L22

But here it's `true` https://github.com/owainlewis/yaml/blob/master/src/yaml/reader.clj#L8

**Comment by owainlewis** [comment]
Thanks. This looks like a mistake as it should be consistent. Will fix.

**Comment by rymndhng** [comment]
Looks like this was solved in https://github.com/owainlewis/yaml/commit/1c41449f4ab561812fbb83ced0c27922ef1d3386

**Comment by owainlewis** [comment]
Closing since it should now be resolved.
