### ISSUE TITLE
Flatland Dependency Issue with JDK11

### ISSUE THREAD

**Issue by defndaines** [owainlewis/yaml#28]
The library is affected by https://github.com/amalloy/ordered/pull/37

Users on JDK11 may encounter errors. Mine manifested because `lein test-refresh` broke for our project with this message:
```
Error refreshing environment: java.lang.IllegalArgumentException: Must hint overloaded method: toArray, compiling:(flatland/ordered/set.clj:12:1)
```
or, more confusingly:
```
Error refreshing environment: java.lang.IllegalAccessError: ordered-set does not exist, compiling:(yaml/reader.clj:1:1)
```

**Comment by danielcompton** [comment]
This is now [released](https://github.com/clj-commons/ordered/releases/tag/1.5.7) in `[org.flatland/ordered "1.5.7"]`.

**Comment by cloojure** [comment]
Could you possibly update your dependencies?  Reading YAML fails under Java 11 because of outdated version dependency on org.flatland/ordered.

`lein ancient` reports:

```
[org.clojure/clojure "1.10.0"] is available but we use "1.6.0" (use :check-clojure to upgrade)
[org.yaml/snakeyaml "1.23"] is available but we use "1.19"
[org.flatland/ordered "1.5.7"] is available but we use "1.5.2"

```

I would also suggest updating Clojure to at least 1.8, and both `ordered` and `snakeyaml` to the latest versions.

**Comment by raszi** [comment]
Could you please release the new version?

**Comment by jvia** [comment]
Any chance this will get a release soon?

**Comment by cloojure** [comment]
As a workaround, I have added YAML parsing here:

- API docs:  https://cloojure.github.io/doc/tupelo/tupelo.parse.yaml.html
- Tests:  https://github.com/cloojure/tupelo/blob/master/test/clj/tst/tupelo/parse/yaml.clj
