### ISSUE TITLE
Need to release a new version with updated org.flatland/ordered dependency

### ISSUE THREAD

**Issue by wiseman** [owainlewis/yaml#34]
The released version of io.forward/yaml 1.09 still has a dependency on org.flatland/ordered 1.5.2, which has [this bug](https://github.com/clj-commons/ordered/issues/40).

`master` has the updated dependency (1.5.7) but doesn't seem to have been released?

**Comment by buntine** [comment]
Bump! This is breaking my build - can we get master released?

**Comment by nickik** [comment]
Bump! This library is a dependence of 'metosin/compojure-api' and it would be great if we could make that Java 11 compatible.

**Comment by owainlewis** [comment]
Sorry for the delay here. Fixed in [io.forward/yaml "1.0.10"]. Please let me know if you have any issues.
